# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  mk_log_config = debug
  mk_ini_config = debug
  mk_sokol_config = debug
  mk_hmm_config = debug
  mk_stb_config = debug
  mk_sqv_config = debug

else ifeq ($(config),release)
  mk_log_config = release
  mk_ini_config = release
  mk_sokol_config = release
  mk_hmm_config = release
  mk_stb_config = release
  mk_sqv_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := mk_log mk_ini mk_sokol mk_hmm mk_stb mk_sqv

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

mk_log:
ifneq (,$(mk_log_config))
	@echo "==== Building mk_log ($(mk_log_config)) ===="
	@${MAKE} --no-print-directory -C .ignore -f mk_log.make config=$(mk_log_config)
endif

mk_ini:
ifneq (,$(mk_ini_config))
	@echo "==== Building mk_ini ($(mk_ini_config)) ===="
	@${MAKE} --no-print-directory -C .ignore -f mk_ini.make config=$(mk_ini_config)
endif

mk_sokol:
ifneq (,$(mk_sokol_config))
	@echo "==== Building mk_sokol ($(mk_sokol_config)) ===="
	@${MAKE} --no-print-directory -C .ignore -f mk_sokol.make config=$(mk_sokol_config)
endif

mk_hmm:
ifneq (,$(mk_hmm_config))
	@echo "==== Building mk_hmm ($(mk_hmm_config)) ===="
	@${MAKE} --no-print-directory -C .ignore -f mk_hmm.make config=$(mk_hmm_config)
endif

mk_stb:
ifneq (,$(mk_stb_config))
	@echo "==== Building mk_stb ($(mk_stb_config)) ===="
	@${MAKE} --no-print-directory -C .ignore -f mk_stb.make config=$(mk_stb_config)
endif

mk_sqv:
ifneq (,$(mk_sqv_config))
	@echo "==== Building mk_sqv ($(mk_sqv_config)) ===="
	@${MAKE} --no-print-directory -C .ignore -f mk_sqv.make config=$(mk_sqv_config)
endif

clean:
	@${MAKE} --no-print-directory -C .ignore -f mk_log.make clean
	@${MAKE} --no-print-directory -C .ignore -f mk_ini.make clean
	@${MAKE} --no-print-directory -C .ignore -f mk_sokol.make clean
	@${MAKE} --no-print-directory -C .ignore -f mk_hmm.make clean
	@${MAKE} --no-print-directory -C .ignore -f mk_stb.make clean
	@${MAKE} --no-print-directory -C .ignore -f mk_sqv.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   mk_log"
	@echo "   mk_ini"
	@echo "   mk_sokol"
	@echo "   mk_hmm"
	@echo "   mk_stb"
	@echo "   mk_sqv"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"