# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  lib_log_config = debug
  lib_sokol_config = debug
  lib_hmm_config = debug
  lib_stb_config = debug
  lib_sepi_config = debug
  tool_lua_config = debug
  app_playground_config = debug
  app_pak_config = debug

else ifeq ($(config),release)
  lib_log_config = release
  lib_sokol_config = release
  lib_hmm_config = release
  lib_stb_config = release
  lib_sepi_config = release
  tool_lua_config = release
  app_playground_config = release
  app_pak_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := lib_log lib_sokol lib_hmm lib_stb lib_sepi tool_lua app_playground app_pak

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lib_log:
ifneq (,$(lib_log_config))
	@echo "==== Building lib_log ($(lib_log_config)) ===="
	@${MAKE} --no-print-directory -C .build -f lib_log.make config=$(lib_log_config)
endif

lib_sokol:
ifneq (,$(lib_sokol_config))
	@echo "==== Building lib_sokol ($(lib_sokol_config)) ===="
	@${MAKE} --no-print-directory -C .build -f lib_sokol.make config=$(lib_sokol_config)
endif

lib_hmm:
ifneq (,$(lib_hmm_config))
	@echo "==== Building lib_hmm ($(lib_hmm_config)) ===="
	@${MAKE} --no-print-directory -C .build -f lib_hmm.make config=$(lib_hmm_config)
endif

lib_stb:
ifneq (,$(lib_stb_config))
	@echo "==== Building lib_stb ($(lib_stb_config)) ===="
	@${MAKE} --no-print-directory -C .build -f lib_stb.make config=$(lib_stb_config)
endif

lib_sepi:
ifneq (,$(lib_sepi_config))
	@echo "==== Building lib_sepi ($(lib_sepi_config)) ===="
	@${MAKE} --no-print-directory -C .build -f lib_sepi.make config=$(lib_sepi_config)
endif

tool_lua:
ifneq (,$(tool_lua_config))
	@echo "==== Building tool_lua ($(tool_lua_config)) ===="
	@${MAKE} --no-print-directory -C .build -f tool_lua.make config=$(tool_lua_config)
endif

app_playground:
ifneq (,$(app_playground_config))
	@echo "==== Building app_playground ($(app_playground_config)) ===="
	@${MAKE} --no-print-directory -C .build -f app_playground.make config=$(app_playground_config)
endif

app_pak:
ifneq (,$(app_pak_config))
	@echo "==== Building app_pak ($(app_pak_config)) ===="
	@${MAKE} --no-print-directory -C .build -f app_pak.make config=$(app_pak_config)
endif

clean:
	@${MAKE} --no-print-directory -C .build -f lib_log.make clean
	@${MAKE} --no-print-directory -C .build -f lib_sokol.make clean
	@${MAKE} --no-print-directory -C .build -f lib_hmm.make clean
	@${MAKE} --no-print-directory -C .build -f lib_stb.make clean
	@${MAKE} --no-print-directory -C .build -f lib_sepi.make clean
	@${MAKE} --no-print-directory -C .build -f tool_lua.make clean
	@${MAKE} --no-print-directory -C .build -f app_playground.make clean
	@${MAKE} --no-print-directory -C .build -f app_pak.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lib_log"
	@echo "   lib_sokol"
	@echo "   lib_hmm"
	@echo "   lib_stb"
	@echo "   lib_sepi"
	@echo "   tool_lua"
	@echo "   app_playground"
	@echo "   app_pak"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"