#!/usr/bin/env lua

-- =====================================================
-- CONFIGURATION TABLE
-- =====================================================
local jobs = {
    -- SAMPLE
    -- {
    --     input_dir    = "src/deps/sepi/templates/",
    --     target_dir   = "src/deps/sepi/generated/",
    --     input_module = "stack.h",
    --     target       = "IONode",
    --     headers      = { "deps/employee.h" }
    --     defines      = { "FOO_BAR" }
    -- },
    -- SEPI LEVEL
    {
        input_dir    = "src/deps/sepi/templates/",
        target_dir   = "src/deps/sepi/generated/",
        input_module = "stack.h",
        target       = "IOItem",
    },
    -- SQV LEVEL
    {
        input_dir    = "src/deps/sepi/templates/",
        target_dir   = "src/generated/",
        input_module = "map.h",
        target       = "PakItem",
    },
    {
        input_dir    = "src/deps/sepi/templates/",
        target_dir   = "src/generated/",
        input_module = "map.h",
        target       = "PakCounter",
    },
}

-- Registry to group files by their target directory
-- Structure: { ["dir/path/"] = { {macro=..., include=...}, ... }, ... }
local master_registry = {}

-- =====================================================
-- GENERATOR ENGINE
-- =====================================================
local function generate(cfg)
    -- 1. Path Logic
    local in_dir  = cfg.input_dir
    local out_dir = cfg.target_dir

    if in_dir:sub(-1)  ~= "/" then in_dir  = in_dir  .. "/" end
    if out_dir:sub(-1) ~= "/" then out_dir = out_dir .. "/" end

    local base_name = cfg.input_module:match("([^/]+)%.h$")
    local output_filename = string.format("%s_%s.h", base_name:lower(), cfg.target:lower())

    local full_input_path  = in_dir  .. cfg.input_module
    local full_output_path = out_dir .. output_filename

    -- 2. Setup Variables
    local target = cfg.target
    local camel  = target:sub(1,1):upper() .. target:sub(2)
    local type_val = camel

    -- 3. Build Blocks
    local header_block = ""
    for _, path in ipairs(cfg.headers or {}) do
        header_block = header_block .. '#include ' .. path .. '\n'
    end

    local define_block = ""
    for _, def in ipairs(cfg.defines or {}) do
        define_block = define_block .. '#define ' .. def .. '\n'
    end

    -- 4. Read Template
    local f = io.open(full_input_path, "r")
    if not f then
        print("Error: Could not find template: " .. full_input_path)
        return false
    end
    local content = f:read("*a")
    f:close()

    -- 5. Substitutions
    content = content:gsub("#define _EXTRA_HEADERS_", header_block)
    content = content:gsub("#define _EXTRA_DEFINES_", define_block)
    content = content:gsub("_Type_", type_val)
    content = content:gsub("_CLASS_", target:upper())
    content = content:gsub("_Class_", camel)
    content = content:gsub("_class_", target:lower())

    -- 6. Add Header Warning
    local warning = "/* THIS IS AN AUTOGENERATED FILE, DO NOT EDIT THIS FILE! */\n\n"
    content = warning .. content

    -- 7. Write Output
    local out = io.open(full_output_path, "w")
    if not out then
        print("Error: Could not write to output: " .. full_output_path)
        return false
    end
    out:write(content)
    out:close()

    -- 8. Format Output
    os.execute(string.format("clang-format -i %s", full_output_path))

    -- 9. Register for Master Header (Grouped by out_dir)
    if not master_registry[out_dir] then master_registry[out_dir] = {} end
    table.insert(master_registry[out_dir], {
        macro = string.format("SEPI_%s_%s_IMPLEMENTATION", base_name:upper(), target:upper()),
        include = output_filename
    })

    return true, output_filename
end

-- =====================================================
-- MAIN EXECUTION LOOP
-- =====================================================
print("Starting code generation...")
print("---------------------------")

for _, job in ipairs(jobs) do
    local success, fname = generate(job)
    if success then
        print(string.format("[SUCCESS] %s -> %s", job.target, fname))
    end
end

-- =====================================================
-- GENERATE MASTER HEADERS (One per directory)
-- =====================================================
for target_dir, files in pairs(master_registry) do
    local master_path = target_dir .. "templates.h"
    local master_content = "/* THIS IS AN AUTOGENERATED MASTER HEADER */\n\n"

    -- Defines
    for _, info in ipairs(files) do
        master_content = master_content .. "#define " .. info.macro .. "\n"
    end

    master_content = master_content .. "\n"

    -- Includes
    for _, info in ipairs(files) do
        master_content = master_content .. '#include "' .. info.include .. '"\n'
    end

    local mf = io.open(master_path, "w")
    if mf then
        mf:write(master_content)
        mf:close()
        os.execute(string.format("clang-format -i %s", master_path))
        print("---------------------------")
        print("[SUCCESS] Master Header Updated: " .. master_path)
    else
        print("[ERROR] Could not write Master Header: " .. master_path)
    end
end

print("Done.")
